### ISSUE TITLE
Serialization fails if error have some null valued property

### ISSUE THREAD

**Issue by grbr** [shokai/socket.io-request#15]
Hi,
There is an issue with serialization of an error
f.e.: I have an error with code === null
https://github.com/shokai/socket.io-request/blob/d14fb520e2127c98a32c4cf0d88b3a7c5ea62c0f/src/error.js#L5
fails because **err** param in that context is a **code** property of an original error

```
    TypeError: Cannot convert undefined or null to object
        at serializeErrorWithoutStack (.../node_modules/socket.io-request/lib/error.js:31:3)
        at convertErrorToObject (.../node_modules/socket.io-request/lib/error.js:43:16)
        at Function.res.error (.../node_modules/socket.io-request/lib/main.js:84:63)
```

**Comment by shokai** [comment]
thank you. I'll check.
